<?
$PERM["about"]["8"]="R";
$PERM["index.php"]["8"]="R";
$PERM["index.php"]["5"]="W";
$PERM["local"]["*"]="R";
$PERM["bitrix"]["*"]="R";
$PERM["/"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM[".top.menu.php"]["8"]="W";
$PERM["events"]["8"]="W";
$PERM["events"]["5"]="W";
$PERM["search"]["5"]="W";
?>